name: hacki
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  algolia: ^1.0.1
  any_link_preview: 2.0.1-rc
  badges: ^2.0.1
  bloc: ^7.0.0
  collection:
  dio: ^4.0.4
  equatable: 2.0.3
  feature_discovery: ^0.14.0
  firebase_analytics: ^8.3.4
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.3.0
  flutter_bloc: ^7.1.0
  flutter_feather_icons: 2.0.0+1
  flutter_html: ^2.2.1
  flutter_linkify: ^5.0.2
  flutter_riverpod: ^0.14.0+3
  flutter_secure_storage: ^5.0.2
  flutter_typeahead: ^3.2.1
  gbk_codec: ^0.4.0
  get_it: 7.2.0
  html: ^0.15.0
  http: ^0.13.3
  in_app_review: ^2.0.3
  intl: ^0.17.0
  objectid: ^2.0.0
  package_info: ^2.0.2
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.10

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/hacki_icon.png


